// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hseqfpfamgdqocueewco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzZXFmcGZhbWdkcW9jdWVld2NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjA3NjMsImV4cCI6MjA2MDI5Njc2M30.7FV4o8qu-_yZt4nDnRghvFULFMDq3uAb3Pxinmlq8dg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);